#page title
page_title                                : Being John Malkovich                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://beingjohnmalkovich.github.io/                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Being John Malkovich                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Mesh Your Face With John Malkovich's

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : HTW iOS Projekt                                
your_link                                 : https://beingjohnmalkovich.github.io/                     
your_city                                 : Berlin                                
email_address                             : beingjmalkovich@outlook.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : benediktviebahn/being-john-malkovich
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  # - title                                 : GitHub Pages Jekyll Theme
  #   description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
  #   fontawesome_icon_name                 : magic
    
  # - title                                 : iPhone Device Preview
  #   description                           : Preview your app in the context of an iPhone device. Five different device colors included.
  #   fontawesome_icon_name                 : mobile

  # - title                                 : Video Support
  #   description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
  #   fontawesome_icon_name                 : play-circle

  # - title                                 : Automatic Icon and Metadata
  #   description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
  #   fontawesome_icon_name                 : sync

  - title                                 : Light & Dark Mode
    description                           : Automatical setting of light or dark mode based on the system configuration on your iPhone.
    fontawesome_icon_name                 : star-half-o
  
  - title                                 : Save Photos 
    description                           : Easy access to all your previously taken meshed photos by saving to the app.
    fontawesome_icon_name                 : folder

  - title                                 : Accessibility
    description                           : Adjust the font size to your liking.
    fontawesome_icon_name                 : low-vision

  - title                                 : Share With Friends
    description                           : Share your meshed photo through all your social media accounts.
    fontawesome_icon_name                 : share-alt

  - title                                 : Local Storage
    description                           : Save your meshed photos locally on your iPhone.
    fontawesome_icon_name                 : download

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"
